name: User cleanup job CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy User cleanup job
    uses: thumperq/cicd/.github/workflows/cdJob.yaml@v0.1.45
    secrets:
      GCP_CREDENTIALS: ${{ vars.GCP_CREDENTIALS }}
      ENVIRONMENT: staging
      DOMAIN_NAME: wms
      SERVICE_NAME: user-cleaner-job
      # the external ip address on port 8200
      VAULT_ADDR: ${{ vars.VAULT_ADDR }}
      VAULT_TOKEN: ${{ vars.VAULT_TOKEN }}
