name: User cleanup job CI

on:
  pull_request:

jobs:
  build-test:
    name: Build and Unit Test User cleanup job
    uses: thumperq/cicd/.github/workflows/ci.yaml@v0.1.3
    secrets:
      GITHUBACTION_TOKEN: ${{ secrets.GITHUBACTION_TOKEN }}
      GITHUBACTION_USERNAME: ${{ secrets.GITHUBACTION_USERNAME }}
      DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
